Adding the conf file and making options for dump, folder archive and maintenance mode.

diff --git a/nextcloud-backup b/nextcloud-backup
--- a/nextcloud-backup
+++ b/nextcloud-backup
@@ -1,27 +1,30 @@
 #!/bin/bash
 
 ## Variables ##
-dryrun="no"
+scriptdir=$(dirname $0)
+scriptname=$(basename $0)
 D="-------"
+database="no"
+folder="no"
+maintmode="no"
 bkpdate=$(date +"%Y%m%d")
-bkplog="/var/log/backups/$bkpdate.log"
-bkpdst="/mnt/backups"
-ncdir="/srv/www/nextcloud"
-direxcl="*/data/updater-*"
-dbhost=$(grep dbhost $ncdir/config/config.php | awk -F "'" '{print $4}' | awk -F ":" '{print $1}')
-dbport=$(grep dbhost $ncdir/config/config.php | awk -F "'" '{print $4}' | awk -F ":" '{print $2}')
-dbuser=$(grep dbuser $ncdir/config/config.php | awk -F "'" '{print $4}')
-dbpwd=$(grep dbpassword $ncdir/config/config.php | awk -F "'" '{print $4}')
-dbname=$(grep dbname $ncdir/config/config.php | awk -F "'" '{print $4}')
+
+## Parameters ##
+if [ -f ${scriptdir}/${scriptname}.conf ] ; then
+	. ${scriptdir}/${scriptname}.conf
+else
+	echo -e "ERROR: Parameter file (${scriptdir}/${scriptname}.conf) not found!"
+fi
 
 ## Functions ##
 # Script usage #
 usage()
 {
-	scriptname=$(basename $0)
-	echo -e "Usage: $scriptname [-d]" 1>&2
-	echo -e " -d: dry-run"
-	exit 1
+	echo -e "Usage: ${scriptname} [-d] [-f] [-m] [-t]" 1>&2
+	echo -e " -d: dumping the nextcloud database"
+	echo -e " -f: archiving the nextcloud folder"
+	echo -e " -m: setting maintenance mode on before backup and off after"
+	echo -e " -t: running in testmode (simulating the backup)"
 }
 
 # Print to log #
@@ -30,11 +33,8 @@ print_log()
 	delimiter="----------------$D-----------------------"
 	logstamp="----- Backup $1: $(date +'%Y-%m-%d') $(date +'%H-%M-%S') -----"
 	case $1 in
-		start)
-			echo -e "\n$delimiter\n$logstamp" >>$bkplog
-			;;
-		end)
-			echo -e "\n$logstamp\n$delimiter\n" >>$bkplog
+		start)	echo -e "\n$delimiter\n$logstamp" >>$bkplog ;;
+		end)	echo -e "\n$logstamp\n$delimiter\n" >>$bkplog ;;
 	esac
 }
 
@@ -43,7 +43,7 @@ maint_mode()
 {
 	mode=$(printf '%s\n' "$1" | awk '{ print toupper($0) }')
 	echo -e "\n[INFO] Maintenance mode $mode" >>$bkplog
-	if [ "$dryrun" == "no"  ] ; then
+	if [ "$testmode" == "no"  ] ; then
 		sudo -u www-data php $ncdir/occ maintenance:mode --$1 >>$bkplog 2>&1
 		if [ $? -ne 0 ] ; then
 			echo -e "[ERROR] Setting maintenance mode '$mode' failed (exit code: $?)" >>$bkplog
@@ -58,7 +58,7 @@ maint_mode()
 db_dump()
 {
 	echo -e "\n[INFO] DataBase Export" >>$bkplog
-	if [ "$dryrun" == "no"  ] ; then
+	if [ "$testmode" == "no"  ] ; then
 		mysqldump --single-transaction -h "$dbhost" -P "$dbport" -u "$dbuser" -p"$dbpwd" "$dbname" > $bkpdst/nextcloud-sqlbkp_$bkpdate.sql 2>>$bkplog
 		if [ $? -ne 0 ] ; then
 			echo -e "[ERROR] DataBase export failed (exit code: $?)" >>$bkplog
@@ -74,7 +74,7 @@ db_dump()
 folder_archive()
 {
 	echo -e "\n[INFO] Folder archival" >>$bkplog
-	if [ "$dryrun" == "no" ] ; then
+	if [ "$testmode" == "no" ] ; then
 		tar -czf $bkpdst/nextcloud-dirbkp_$bkpdate.tgz --directory="$ncdir" --exclude="$direxcl" . 2>>$bkplog
 		if [ $? -ne 0 ] ; then
 			echo -e "[ERROR] Folder archive failed (exit code: $?)" >>$bkplog
@@ -87,24 +87,25 @@ folder_archive()
 }
 
 ## Main ##
-while getopts ":d" option
+while getopts ":dfmt" option
 do
 	case $option in
-		d)
-			dryrun="yes"
-			D="DRY-RUN"
-			;;
+		d)	database="yes" ;;
+		f)	folder="yes" ;;
+		m)	maintmode="yes" ;;	
+		t)	testmode="yes" ; D="DRY-RUN" ;;
 		*)
 			echo -e "$OPTARG: invalid option\n"
 			usage
+			exit 2
 			;;
 	esac
 done
 
 print_log start
-maint_mode on
-db_dump
-folder_archive
-maint_mode off
+if [ "$maintmode" == "yes" ] ; then maint_mode on ; fi
+if [ "$database" == "yes" ] ; then db_dump ; fi
+if [ "$folder" == "yes" ] ; then folder_archive ; fi
+if [ "$maintmode" == "yes" ] ; then maint_mode off ; fi
 print_log end
 exit 0
